import { ValueOf } from "type-fest";

export const validLanguages = [
  "aa",
  "ab",
  "af",
  "ak",
  "sq",
  "am",
  "ar",
  "an",
  "hy",
  "as",
  "av",
  "ae",
  "ay",
  "az",
  "ba",
  "bm",
  "eu",
  "be",
  "bn",
  "bh",
  "bi",
  "bs",
  "br",
  "bg",
  "my",
  "ca",
  "ch",
  "ce",
  "zh",
  "cv",
  "kw",
  "co",
  "cr",
  "cs",
  "da",
  "dv",
  "nl",
  "dz",
  "en",
  "eo",
  "et",
  "ee",
  "fo",
  "fj",
  "fi",
  "fr",
  "fy",
  "ff",
  "ka",
  "de",
  "gd",
  "ga",
  "gl",
  "gv",
  "el",
  "gn",
  "gu",
  "ht",
  "ha",
  "he",
  "hz",
  "hi",
  "ho",
  "hr",
  "hu",
  "ig",
  "is",
  "io",
  "ii",
  "iu",
  "ie",
  "ia",
  "id",
  "ik",
  "it",
  "jv",
  "ja",
  "kl",
  "kn",
  "ks",
  "kr",
  "kk",
  "km",
  "ki",
  "rw",
  "ky",
  "kv",
  "kg",
  "ko",
  "kj",
  "ku",
  "lo",
  "la",
  "lv",
  "li",
  "ln",
  "lt",
  "lb",
  "lu",
  "lg",
  "mk",
  "mh",
  "ml",
  "mi",
  "mr",
  "ms",
  "mg",
  "mt",
  "mn",
  "na",
  "nv",
  "nr",
  "nd",
  "ng",
  "ne",
  "nn",
  "nb",
  "no",
  "ny",
  "oc",
  "oj",
  "or",
  "om",
  "os",
  "pa",
  "fa",
  "pi",
  "pl",
  "pt",
  "ps",
  "qu",
  "rm",
  "ro",
  "rn",
  "ru",
  "sg",
  "sa",
  "si",
  "sk",
  "sl",
  "se",
  "sm",
  "sn",
  "sd",
  "so",
  "st",
  "es",
  "sc",
  "sr",
  "ss",
  "su",
  "sw",
  "sv",
  "ty",
  "ta",
  "tt",
  "te",
  "tg",
  "tl",
  "th",
  "bo",
  "ti",
  "to",
  "tn",
  "ts",
  "tk",
  "tr",
  "tw",
  "ug",
  "uk",
  "ur",
  "uz",
  "ve",
  "vi",
  "vo",
  "cy",
  "wa",
  "wo",
  "xh",
  "yi",
  "yo",
  "za",
  "zu"
] as const;

export type Language = ValueOf<typeof validLanguages>;

export const languages = new Map<Language, string>([
  ["aa", "Afar"],
  ["ab", "Abkhazian"],
  ["af", "Afrikaans"],
  ["ak", "Akan"],
  ["sq", "Albanian"],
  ["am", "Amharic"],
  ["ar", "Arabic"],
  ["an", "Aragonese"],
  ["hy", "Armenian"],
  ["as", "Assamese"],
  ["av", "Avaric"],
  ["ae", "Avestan"],
  ["ay", "Aymara"],
  ["az", "Azerbaijani"],
  ["ba", "Bashkir"],
  ["bm", "Bambara"],
  ["eu", "Basque"],
  ["be", "Belarusian"],
  ["bn", "Bengali"],
  ["bh", "Bihari languages"],
  ["bi", "Bislama"],
  ["bs", "Bosnian"],
  ["br", "Breton"],
  ["bg", "Bulgarian"],
  ["my", "Burmese"],
  ["ca", "Catalan; Valencian"],
  ["ch", "Chamorro"],
  ["ce", "Chechen"],
  ["zh", "Chinese"],
  ["cv", "Chuvash"],
  ["kw", "Cornish"],
  ["co", "Corsican"],
  ["cr", "Cree"],
  ["cs", "Czech"],
  ["da", "Danish"],
  ["dv", "Divehi; Dhivehi; Maldivian"],
  ["nl", "Dutch; Flemish"],
  ["dz", "Dzongkha"],
  ["en", "English"],
  ["eo", "Esperanto"],
  ["et", "Estonian"],
  ["ee", "Ewe"],
  ["fo", "Faroese"],
  ["fj", "Fijian"],
  ["fi", "Finnish"],
  ["fr", "French"],
  ["fy", "Western Frisian"],
  ["ff", "Fulah"],
  ["ka", "Georgian"],
  ["de", "German"],
  ["gd", "Gaelic; Scottish Gaelic"],
  ["ga", "Irish"],
  ["gl", "Galician"],
  ["gv", "Manx"],
  ["el", "Greek, Modern (1453-)"],
  ["gn", "Guarani"],
  ["gu", "Gujarati"],
  ["ht", "Haitian; Haitian Creole"],
  ["ha", "Hausa"],
  ["he", "Hebrew"],
  ["hz", "Herero"],
  ["hi", "Hindi"],
  ["ho", "Hiri Motu"],
  ["hr", "Croatian"],
  ["hu", "Hungarian"],
  ["ig", "Igbo"],
  ["is", "Icelandic"],
  ["io", "Ido"],
  ["ii", "Sichuan Yi; Nuosu"],
  ["iu", "Inuktitut"],
  ["ie", "Interlingue; Occidental"],
  ["ia", "Interlingua (International Auxiliary Language Association)"],
  ["id", "Indonesian"],
  ["ik", "Inupiaq"],
  ["it", "Italian"],
  ["jv", "Javanese"],
  ["ja", "Japanese"],
  ["kl", "Kalaallisut; Greenlandic"],
  ["kn", "Kannada"],
  ["ks", "Kashmiri"],
  ["kr", "Kanuri"],
  ["kk", "Kazakh"],
  ["km", "Central Khmer"],
  ["ki", "Kikuyu; Gikuyu"],
  ["rw", "Kinyarwanda"],
  ["ky", "Kirghiz; Kyrgyz"],
  ["kv", "Komi"],
  ["kg", "Kongo"],
  ["ko", "Korean"],
  ["kj", "Kuanyama; Kwanyama"],
  ["ku", "Kurdish"],
  ["lo", "Lao"],
  ["la", "Latin"],
  ["lv", "Latvian"],
  ["li", "Limburgan; Limburger; Limburgish"],
  ["ln", "Lingala"],
  ["lt", "Lithuanian"],
  ["lb", "Luxembourgish; Letzeburgesch"],
  ["lu", "Luba-Katanga"],
  ["lg", "Ganda"],
  ["mk", "Macedonian"],
  ["mh", "Marshallese"],
  ["ml", "Malayalam"],
  ["mi", "Maori"],
  ["mr", "Marathi"],
  ["ms", "Malay"],
  ["mg", "Malagasy"],
  ["mt", "Maltese"],
  ["mn", "Mongolian"],
  ["na", "Nauru"],
  ["nv", "Navajo; Navaho"],
  ["nr", "Ndebele, South; South Ndebele"],
  ["nd", "Ndebele, North; North Ndebele"],
  ["ng", "Ndonga"],
  ["ne", "Nepali"],
  ["nn", "Norwegian Nynorsk; Nynorsk, Norwegian"],
  ["nb", "Bokmål, Norwegian; Norwegian Bokmål"],
  ["no", "Norwegian"],
  ["ny", "Chichewa; Chewa; Nyanja"],
  ["oc", "Occitan (post 1500)"],
  ["oj", "Ojibwa"],
  ["or", "Oriya"],
  ["om", "Oromo"],
  ["os", "Ossetian; Ossetic"],
  ["pa", "Panjabi; Punjabi"],
  ["fa", "Persian"],
  ["pi", "Pali"],
  ["pl", "Polish"],
  ["pt", "Portuguese"],
  ["ps", "Pushto; Pashto"],
  ["qu", "Quechua"],
  ["rm", "Romansh"],
  ["ro", "Romanian; Moldavian; Moldovan"],
  ["rn", "Rundi"],
  ["ru", "Russian"],
  ["sg", "Sango"],
  ["sa", "Sanskrit"],
  ["si", "Sinhala; Sinhalese"],
  ["sk", "Slovak"],
  ["sl", "Slovenian"],
  ["se", "Northern Sami"],
  ["sm", "Samoan"],
  ["sn", "Shona"],
  ["sd", "Sindhi"],
  ["so", "Somali"],
  ["st", "Sotho, Southern"],
  ["es", "Spanish; Castilian"],
  ["sc", "Sardinian"],
  ["sr", "Serbian"],
  ["ss", "Swati"],
  ["su", "Sundanese"],
  ["sw", "Swahili"],
  ["sv", "Swedish"],
  ["ty", "Tahitian"],
  ["ta", "Tamil"],
  ["tt", "Tatar"],
  ["te", "Telugu"],
  ["tg", "Tajik"],
  ["tl", "Tagalog"],
  ["th", "Thai"],
  ["bo", "Tibetan"],
  ["ti", "Tigrinya"],
  ["to", "Tonga (Tonga Islands)"],
  ["tn", "Tswana"],
  ["ts", "Tsonga"],
  ["tk", "Turkmen"],
  ["tr", "Turkish"],
  ["tw", "Twi"],
  ["ug", "Uighur; Uyghur"],
  ["uk", "Ukrainian"],
  ["ur", "Urdu"],
  ["uz", "Uzbek"],
  ["ve", "Venda"],
  ["vi", "Vietnamese"],
  ["vo", "Volapük"],
  ["cy", "Welsh"],
  ["wa", "Walloon"],
  ["wo", "Wolof"],
  ["xh", "Xhosa"],
  ["yi", "Yiddish"],
  ["yo", "Yoruba"],
  ["za", "Zhuang; Chuang"],
  ["zu", "Zulu"]
]);
