name: Publish webapp
on: [workflow_dispatch]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - uses: actions/checkout@v3
        with:
          path: "main"
          ref: "main"
      - uses: actions/checkout@v3
        with:
          path: "pages"
          ref: "pages"
      - name: Build and publish app
        run: |
          cd "$GITHUB_WORKSPACE/main"
          yarn install
          yarn build
          cd "$GITHUB_WORKSPACE/pages"
          git clean -fd
          cp -r ../main/dist .
          git add .
          git commit -m "Update web app"
          git push origin pages
